### ISSUE TITLE
Add tests to source tarball

### ISSUE THREAD

**Issue by fabaff** [hfurubotten/enturclient#13]
For the Fedora RPM packages we like to run the available tests during the build process. Could you please make a new release that contains the tests?

Thanks.

**Comment by hfurubotten** [comment]
I have now released a [new beta version](https://github.com/hfurubotten/enturclient/releases/tag/v0.2.2-beta.5) that has the `tests` folder included in the sdist. Could you take a look through the linked artifact and see if it's as expected?

If everything is good and usable for the Fedora RPM, I will need to take a few looks through my earlier changes and just make sure those doesn't make any harm before releasing a new stable version.

**Comment by fabaff** [comment]
Yes, that would work.

I submitted the [Nix package](https://github.com/NixOS/nixpkgs/pull/127539) without running the tests for now.
