### ISSUE TITLE
More than next two busses

### ISSUE THREAD

**Issue by oyvindhauge** [hfurubotten/enturclient#3]
First of all, excellent work @hfurubotten!

Feature request: As far as I understand it is only possible to get info for the two next busses. As a user I would like to be to increase that number of busses/departures I get information for, to see several busses. This could for instance be done through a configurable value similar to the white listing suggested in issue 1. For instance one of the below:
departures_visible_number: 4 
departures_visible_next_mins: 60

**Comment by hfurubotten** [comment]
There is no limitations in the API for getting more than two departures from the client. I just started with two for getting it started with something at least, and unfortunately things started to revolve around that a bit, so it needs some rewrite to extend it further now. I'll see if I can fix that, and find a way to make it more generic for cases like this.

**Comment by hfurubotten** [comment]
The client now support number of departures as a parameter on init, so should support fetching any number of departures and is accessible as an array. Will close this issue here now.
