### ISSUE TITLE
Home Assitant sensor also showing arriving buses at last stop

### ISSUE THREAD

**Issue by flinkebernt** [hfurubotten/enturclient#4]
Hi,
This might be an edge case, but anyhow. I use the entur-sensor in Home Assistant to show departures from a couple of stops. At one of my stops (which also is the last on a route) it shows buses arriving as well. On Enturs website only the departures are shown. 

In the attached screenshot you can see the bus that has route "63 Sylling" at 09:55. This is actually a bus' last stop. Is it somehow possible to see only the departures - not the arrivals?

![capture](https://user-images.githubusercontent.com/5722154/52329098-0e48fe80-29f2-11e9-9b6f-bd6af13d4fa0.PNG)

PS: I imagine it might be that Brakar have set this up wrong at their side, as platform 28962 actually has no arrivals or departures.

**Comment by hfurubotten** [comment]
Hi! 
I actually have the same problem with one of my NSB monitoring, but haven't spent much time trying to solve it, even tho it's a bit annoying. So I believe it's a thing on all endstops/endstations.

Took a look at the API again, and it looks like it can only show lines which take passengers on the stop by having something like this: 
```graphql
estimatedCalls(
    omitNonBoarding: true
  ) { ...estimatedCallFields }
```

I'll see if I can get that option in with next release.

**Comment by hfurubotten** [comment]
If it should contain arriving only transport from a stop place is now configurable on the latest release of the client, so will close the issue here now, but will strive to get it through to HA soon too.
